/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IChemJson,
  IDisplayOptions,
} from '@openchemistry/types';


export namespace Components {

  interface OcMoleculeVtkjs {
    'cjson': IChemJson;
    'options': IDisplayOptions;
    'rotate': boolean;
  }
  interface OcMoleculeVtkjsAttributes extends StencilHTMLAttributes {
    'cjson'?: IChemJson;
    'options'?: IDisplayOptions;
    'rotate'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OcMoleculeVtkjs': Components.OcMoleculeVtkjs;
  }

  interface StencilIntrinsicElements {
    'oc-molecule-vtkjs': Components.OcMoleculeVtkjsAttributes;
  }


  interface HTMLOcMoleculeVtkjsElement extends Components.OcMoleculeVtkjs, HTMLStencilElement {}
  var HTMLOcMoleculeVtkjsElement: {
    prototype: HTMLOcMoleculeVtkjsElement;
    new (): HTMLOcMoleculeVtkjsElement;
  };

  interface HTMLElementTagNameMap {
    'oc-molecule-vtkjs': HTMLOcMoleculeVtkjsElement
  }

  interface ElementTagNameMap {
    'oc-molecule-vtkjs': HTMLOcMoleculeVtkjsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
