/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  INormalModeOptions,
  IVibrations,
} from '@openchemistry/types';


export namespace Components {

  interface OcVibrationalSpectrum {
    'options': INormalModeOptions;
    'vibrations': IVibrations;
  }
  interface OcVibrationalSpectrumAttributes extends StencilHTMLAttributes {
    'onBarSelected'?: (event: CustomEvent) => void;
    'options'?: INormalModeOptions;
    'vibrations'?: IVibrations;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OcVibrationalSpectrum': Components.OcVibrationalSpectrum;
  }

  interface StencilIntrinsicElements {
    'oc-vibrational-spectrum': Components.OcVibrationalSpectrumAttributes;
  }


  interface HTMLOcVibrationalSpectrumElement extends Components.OcVibrationalSpectrum, HTMLStencilElement {}
  var HTMLOcVibrationalSpectrumElement: {
    prototype: HTMLOcVibrationalSpectrumElement;
    new (): HTMLOcVibrationalSpectrumElement;
  };

  interface HTMLElementTagNameMap {
    'oc-vibrational-spectrum': HTMLOcVibrationalSpectrumElement
  }

  interface ElementTagNameMap {
    'oc-vibrational-spectrum': HTMLOcVibrationalSpectrumElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
