/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IChemJson,
  IDisplayOptions,
} from '@openchemistry/types';


export namespace Components {

  interface OcMoleculeMoljs {
    'cjson': IChemJson | string;
    'options': IDisplayOptions;
    'rotate': boolean;
  }
  interface OcMoleculeMoljsAttributes extends StencilHTMLAttributes {
    'cjson'?: IChemJson | string;
    'options'?: IDisplayOptions;
    'rotate'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OcMoleculeMoljs': Components.OcMoleculeMoljs;
  }

  interface StencilIntrinsicElements {
    'oc-molecule-moljs': Components.OcMoleculeMoljsAttributes;
  }


  interface HTMLOcMoleculeMoljsElement extends Components.OcMoleculeMoljs, HTMLStencilElement {}
  var HTMLOcMoleculeMoljsElement: {
    prototype: HTMLOcMoleculeMoljsElement;
    new (): HTMLOcMoleculeMoljsElement;
  };

  interface HTMLElementTagNameMap {
    'oc-molecule-moljs': HTMLOcMoleculeMoljsElement
  }

  interface ElementTagNameMap {
    'oc-molecule-moljs': HTMLOcMoleculeMoljsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
